# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'createset_ui.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.ApplicationModal)
        Dialog.resize(462, 333)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setScaledContents(False)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.buttonAdd = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.buttonAdd.setFont(font)
        self.buttonAdd.setObjectName("buttonAdd")
        self.horizontalLayout.addWidget(self.buttonAdd)
        self.buttonRemove = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.buttonRemove.setFont(font)
        self.buttonRemove.setObjectName("buttonRemove")
        self.horizontalLayout.addWidget(self.buttonRemove)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.input_layout = QtWidgets.QVBoxLayout()
        self.input_layout.setObjectName("input_layout")
        self.input_1 = QtWidgets.QLineEdit(Dialog)
        self.input_1.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.input_1.setText("")
        self.input_1.setObjectName("input_1")
        self.input_layout.addWidget(self.input_1)
        self.input_2 = QtWidgets.QLineEdit(Dialog)
        self.input_2.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.input_2.setObjectName("input_2")
        self.input_layout.addWidget(self.input_2)
        self.input_3 = QtWidgets.QLineEdit(Dialog)
        self.input_3.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.input_3.setObjectName("input_3")
        self.input_layout.addWidget(self.input_3)
        self.input_4 = QtWidgets.QLineEdit(Dialog)
        self.input_4.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.input_4.setObjectName("input_4")
        self.input_layout.addWidget(self.input_4)
        self.input_5 = QtWidgets.QLineEdit(Dialog)
        self.input_5.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.input_5.setObjectName("input_5")
        self.input_layout.addWidget(self.input_5)
        self.input_6 = QtWidgets.QLineEdit(Dialog)
        self.input_6.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.input_6.setObjectName("input_6")
        self.input_layout.addWidget(self.input_6)
        self.verticalLayout_2.addLayout(self.input_layout)
        spacerItem1 = QtWidgets.QSpacerItem(20, 21, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setFocusPolicy(QtCore.Qt.TabFocus)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_2.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Create Set"))
        self.label.setText(_translate("Dialog", "Serial Numbers:"))
        self.buttonAdd.setToolTip(_translate("Dialog", "Ctrl-A"))
        self.buttonAdd.setText(_translate("Dialog", "+"))
        self.buttonRemove.setToolTip(_translate("Dialog", "Ctrl-R"))
        self.buttonRemove.setText(_translate("Dialog", "-"))
