PORT = 6969

URL_CONFIGURATION = f"http://localhost:{PORT}/configuration"
URL_MODEM_STATUS = f"http://localhost:{PORT}/modemstatus"
URL_SOFTWARE_UPGRADE = f"http://localhost:{PORT}/softwareupgrade"
URL_UPGRADE_LOG = "/Users/charles/PycharmProjects/LWTest/tests/mock/software_upgrade_example_1.html"
# . URL_UPGRADE_LOG = r"LWTest\tests\webpages\software upgrade example of failure.html"
URL_SENSOR_DATA = f"http://localhost:{PORT}/sensordata"
URL_TEMPERATURE = f"http://localhost:{PORT}/temperaturescale"
URL_RAW_CONFIGURATION = f"http://localhost:{PORT}/rawconfig"
URL_CALIBRATE = f"http://localhost:{PORT}/calibrate"
URL_FAULT_CURRENT = f"http://localhost:{PORT}/faultcurrent"
URL_VOLTAGE_RIDE_THROUGH = f"http://localhost:{PORT}/voltageridethrough"
URL_LOG_FILES = f"http://localhost:{PORT}/static/logfiles.zip"
URL_LOGIN = f"http://localhost:{PORT}/login"
URL_DATE_TIME = f"http://localhost:{PORT}/date_and_time"
